### ISSUE TITLE
program should be stored in localstore not URL

### ISSUE THREAD

**Issue by rzeta0** [leanprover-community/lean4web#27]
As far as I can see the current code is stored in the URL.

I don't believe this will scale to medium-to-longer code. 

The web service for prolog https://swish.swi-prolog.org doesn't store code in the URL but appears to store it locally using the web local storage API https://www.w3schools.com/html/html5_webstorage.asp

This has 3 benefits:

- larger storage capacity
- increased performance
- no passing of code to server

Sadly I am no expert at coding so this is a suggestion, not a PR.

**Comment by joneugster** [comment]
Currently the intended usecase is foremost to be able to easily run small snippets from Zulip and to easily create such MWEs for sharing on the chat service, which is why we are currently always putting the code into the URL.

However, having a share button that creates this URL and using browser storage meanwhile could be an idea.

The drawback might be that you either cannot have multiple tabs with different code open or that you might loose your code on sudden internet loss or accidential reload of the page

**Comment by j3parker** [comment]
I'm a big fan of being able to copy+paste URLs to share code, and having the state be immediately reflected into the address bar.
I opened #36 as a middle ground so that the URLs can "scale" further.
